#!/usr/bin/env python3
"""
Generate sample CSV file for testing.
"""

import csv
import random
from datetime import datetime

def generate_sample_csv(filename='test/sample-users-large.csv', num_users=100):
    """Generate a larger sample CSV file for testing."""
    
    first_names = ['John', 'Jane', 'Bob', 'Alice', 'Charlie', 'Diana', 'Edward', 'Fiona', 'George', 'Hannah',
                   'Ian', 'Julia', 'Kevin', 'Laura', 'Michael', 'Nancy', 'Oscar', 'Patricia', 'Quinn', 'Rachel']
    
    last_names = ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis', 'Rodriguez', 'Martinez',
                  'Hernandez', 'Lopez', 'Gonzalez', 'Wilson', 'Anderson', 'Thomas', 'Taylor', 'Moore', 'Jackson', 'Martin']
    
    employment_statuses = ['full-time', 'part-time', 'self-employed', 'contract']
    
    users = []
    
    for i in range(num_users):
        first = random.choice(first_names)
        last = random.choice(last_names)
        email = f"{first.lower()}.{last.lower()}{i}@example.com"
        
        # Generate realistic income (30k - 150k)
        monthly_income = random.randint(30000, 150000)
        
        # Credit score (300-850)
        credit_score = random.randint(600, 850)
        
        # Employment status
        employment = random.choice(employment_statuses)
        
        # Age (21-65)
        age = random.randint(21, 65)
        
        users.append({
            'user_id': '',  # Will be generated by database
            'email': email,
            'monthly_income': monthly_income,
            'credit_score': credit_score,
            'employment_status': employment,
            'age': age
        })
    
    # Write to CSV
    with open(filename, 'w', newline='') as csvfile:
        fieldnames = ['user_id', 'email', 'monthly_income', 'credit_score', 'employment_status', 'age']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        
        writer.writeheader()
        for user in users:
            writer.writerow(user)
    
    print(f"✅ Generated {num_users} sample users in {filename}")

if __name__ == '__main__':
    generate_sample_csv()
